services:
  baber-web:
    image: aldovadev/barber-web:latest
    container_name: barber-web
    restart: unless-stopped
    environment:
      - VITE_BASE_URL_MINIO=${VITE_BASE_URL_MINIO}
      - VITE_BASE_URL_SQUARE=${VITE_BASE_URL_SQUARE}
      - VITE_API_KEY_SQUARE=${VITE_API_KEY_SQUARE}
    ports:
      - "4080:80"
    networks:
      - barber_default

networks:
  barber_default:
    external: true
